services:
  - type: web
    name: sahibinden-bot
    env: node
    buildCommand: npm install && npx playwright install-deps chromium && npx playwright install chromium && node bot.js
    startCommand: npm start
